# Generated by Django 4.2.6 on 2023-10-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('desc', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
            ],
        ),
    ]
