# Generated by Django 4.2.6 on 2023-10-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usedbooks',
            old_name='desc',
            new_name='category',
        ),
    ]
