# Generated by Django 4.2.6 on 2023-10-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_rename_desc_usedbooks_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_no', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
