# Generated by Django 4.2.6 on 2023-10-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0003_registeredusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredusers',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='registeredusers',
            name='last_name',
        ),
    ]
